### PR TITLE
Browser/preview

### PR DESCRIPTION
**Pull request by kzidane**
Demo: [browser.zip](https://github.com/cs50/harvard.cs50.simple/files/732550/browser.zip)

Relevant PR: https://github.com/cs50/phpliteadmin/pull/5

cc @dmalan

### CODE REVIEW

**Comment by kzidane** [comment]
Waiting for C9 to support setting and changing preview tab titles. Purposed an approach, but they might want to find a more general approach per https://github.com/c9/c9.ide.preview.browser/pull/3#issuecomment-277022673!

**Comment by dmalan** [comment]
Conflict in `simple.js` now, but otherwise :shipit: !

**Comment by kzidane** [comment]
Closing in favor of cs50/harvard.cs50.phpliteadmin. Will revisit when needed.

**Comment by dmalan** [comment]
:thumbsup:

**Pull request closed without merging**
