### PR TITLE
simplified imgeditor

### PR DESCRIPTION
**Pull request by kzidane**
imgeditor

### CODE REVIEW

**Comment by kzidane** [comment]
Actually there seems to be a bug in the label that I just noticed in the gif. Will push a fix shortly.

**Comment by kzidane** [comment]
Should be fixed. However, there's a bug in Cloud9's `imgeditor` whereby zoom level isn't set correctly after workspace reload. I'll PR them with a fix soon.

**Comment by dmalan** [comment]
Are those standard buttons, specifically the dark color? Should we try centering in the tab after all? Seem a bit awkward there. Else top-right as you proposed, but I worry those'll be overlooked with higher probability.

**Comment by kzidane** [comment]
Yes, but we can change the colors if we want. And sure, center feels better
maybe.

Kareem

**Comment by dmalan** [comment]
Let's try making the buttons the same color as the tab but with a darker
outline in day mode, and a lighter outline in night mode?

**Comment by kzidane** [comment]
@dmalan how does that look?

imgeditor

**Pull request merged**
