### PR TITLE
default settings

### PR DESCRIPTION
**Pull request by kzidane**

### CODE REVIEW

**Comment by kzidane** [comment]
While the issue per SO was with .Table, and .query, the issue on FB was
with .Column, and .Text. After more googling, realized it might be a better
to ignore all no-member errors for the SQLAlchemy class using
--ignored-classes per https://docs.pylint.org/en/1.6.0/features.html#id28?
Ignoring db.* won't work in case the variable was named something else.

**Comment by dmalan** [comment]
Sure, `--ignored-classes` seems more robust, even though it might hide actually incorrect usage.

**Comment by dmalan** [comment]
Actually, is it definitely `SQLAlchemy` or `flask_sqlalchemy` that we'd want?

**Comment by kzidane** [comment]
@dmalan the referenced errors were related to `SQLAlchemy`.

**Pull request merged**
